# Generated by Django 3.0.2 on 2020-01-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_auto_20200123_0047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='speciality',
            options={'ordering': ['name'], 'verbose_name': 'Speciality', 'verbose_name_plural': 'Specialities'},
        ),
        migrations.AlterField(
            model_name='url',
            name='url_address',
            field=models.CharField(max_length=250),
        ),
    ]
