# Generated by Django 3.0.2 on 2020-01-16 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contacts', 'verbose_name_plural': 'Contact Us'},
        ),
    ]
