# Generated by Django 3.0.2 on 2020-01-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20200116_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
